require 'rails_helper'

RSpec.describe Post do
  describe 'associations' do
    it { is_expected.to belong_to(:repository) }
  end

  describe 'validations' do
    it { is_expected.to validate_presence_of(:title) }
    it { is_expected.to validate_presence_of(:body) }
    it { is_expected.to validate_presence_of(:status) }
    it { is_expected.to validate_presence_of(:review_status) }
    it { is_expected.to validate_presence_of(:review_attempts) }
    it { is_expected.to validate_numericality_of(:review_attempts).is_greater_than_or_equal_to(0) }
  end

  describe 'enums' do
    it { is_expected.to define_enum_for(:status).with_values(draft: 'draft', published: 'published', skipped: 'skipped').backed_by_column_of_type(:string) }

    it { is_expected.to define_enum_for(:review_status).with_values(
      not_reviewed: 'not_reviewed',
      approved: 'approved',
      approved_with_retry: 'approved_with_retry',
      approved_with_issues: 'approved_with_issues'
    ).backed_by_column_of_type(:string) }

    it 'defaults to draft status' do
      post = Post.new
      expect(post.status).to eq('draft')
    end

    it 'defaults to not_reviewed review status' do
      post = Post.new
      expect(post.review_status).to eq('not_reviewed')
    end

    it 'defaults to 0 review attempts' do
      post = Post.new
      expect(post.review_attempts).to eq(0)
    end
  end

  describe 'scopes' do
    let(:repository) { create(:repository) }
    let!(:draft_post) { create(:post, repository: repository, status: :draft) }
    let!(:published_post1) { create(:post, :published, repository: repository, published_at: 2.days.ago) }
    let!(:published_post2) { create(:post, :published, repository: repository, published_at: 1.day.ago) }
    let!(:skipped_post) { create(:post, :skipped, repository: repository) }

    describe '.published' do
      it 'returns only published posts' do
        expect(Post.published).to contain_exactly(published_post1, published_post2)
      end

      it 'orders by published_at descending' do
        expect(Post.published.to_a).to eq([published_post2, published_post1])
      end
    end

    describe '.recent' do
      it 'orders by created_at descending' do
        posts = Post.recent.to_a
        expect(posts.first.created_at).to be >= posts.last.created_at
      end
    end
  end

  describe 'status transitions' do
    let(:post) { create(:post) }

    it 'can transition from draft to published' do
      post.update(status: :published)
      expect(post.published?).to be true
    end

    it 'can transition from draft to skipped' do
      post.update(status: :skipped)
      expect(post.skipped?).to be true
    end
  end

  describe 'review_issues serialization' do
    let(:repository) { create(:repository) }
    let(:issues) do
      [
        {
          "category" => "guideline",
          "severity" => "warning",
          "description" => "Test issue",
          "suggestion" => "Fix it"
        }
      ]
    end

    it 'serializes and deserializes review_issues as JSON' do
      post = Post.create!(
        repository: repository,
        title: "Test Post",
        body: "Test content",
        review_issues: issues
      )

      post.reload
      expect(post.review_issues).to eq(issues)
    end

    it 'can store empty array' do
      post = Post.create!(
        repository: repository,
        title: "Test Post",
        body: "Test content",
        review_issues: []
      )

      post.reload
      expect(post.review_issues).to eq([])
    end

    it 'can store nil' do
      post = Post.create!(
        repository: repository,
        title: "Test Post",
        body: "Test content",
        review_issues: nil
      )

      post.reload
      expect(post.review_issues).to be_nil
    end
  end

  describe '#to_html' do
    let(:repository) { create(:repository) }
    let(:post) do
      create(:post,
        repository: repository,
        body: <<~MARKDOWN
          # Test Article Title

          This is the main content of the article.

          ## Section 1

          Some content here.

          ---
          * **Primary Source**: [PR #123](https://github.com/test/test/pull/123)
          * **Generated by**: Claude Sonnet 4.5 for DiffDaily
        MARKDOWN
      )
    end

    it 'converts markdown to HTML' do
      html = post.to_html
      expect(html).to include('<p>This is the main content')
      expect(html).to include('<h2>Section 1</h2>')
    end

    it 'removes leading H1 heading' do
      html = post.to_html
      expect(html).not_to include('Test Article Title')
    end

    it 'removes trailing metadata block' do
      html = post.to_html
      expect(html).not_to include('Primary Source')
      expect(html).not_to include('Generated by')
    end

    it 'returns safe HTML' do
      html = post.to_html
      expect(html).to be_html_safe
    end

    context 'with mermaid diagram' do
      let(:post) do
        create(:post,
          repository: repository,
          body: <<~MARKDOWN
            # Title

            ```mermaid
            graph TD
              A[Start] --> B[End]
            ```
          MARKDOWN
        )
      end

      it 'renders mermaid diagram container' do
        html = post.to_html
        expect(html).to include('data-controller="mermaid"')
        expect(html).to include('mermaid-diagram')
      end
    end

    context 'with code block' do
      let(:post) do
        create(:post,
          repository: repository,
          body: <<~MARKDOWN
            # Title

            ```ruby
            def hello
              puts "Hello, World!"
            end
            ```
          MARKDOWN
        )
      end

      it 'renders code block with syntax highlighting class' do
        html = post.to_html
        expect(html).to include('language-ruby')
        expect(html).to include('def hello')
      end
    end
  end
end
