class Post < ApplicationRecord
  belongs_to :repository

  enum :status, { draft: "draft", published: "published", skipped: "skipped" }, default: :draft
  enum :review_status, {
    not_reviewed: "not_reviewed",               # 精査未実施（後方互換性）
    approved: "approved",                       # 1回目で承認
    approved_with_retry: "approved_with_retry", # リトライ後に承認
    approved_with_issues: "approved_with_issues" # 問題ありだが上限到達後に承認
  }, default: :not_reviewed

  validates :title, presence: true
  validates :body, presence: true
  validates :status, presence: true
  validates :review_status, presence: true
  validates :review_attempts, presence: true, numericality: { greater_than_or_equal_to: 0 }

  # review_issuesをJSON形式で保存
  serialize :review_issues, coder: JSON

  scope :published, -> { where(status: :published).order(published_at: :desc) }
  scope :recent, -> { order(created_at: :desc) }

  # MarkdownをHTMLに変換する
  #
  # @return [String] HTMLに変換されたbody
  def to_html
    # 記事本文から重複部分を削除
    cleaned_body = body.dup

    # 先頭のH1見出しを削除（タイトルと重複するため）
    cleaned_body = cleaned_body.sub(/\A#\s+.*?\n+/, '')

    # 末尾のメタデータブロックを削除（フッターで表示するため）
    # パターン: "---" で始まり、"Primary Source" と "Generated by" を含む部分
    cleaned_body = cleaned_body.sub(/\n*---+\n\*\s*\*\*Primary Source\*\*:.*?\n\*\s*\*\*Generated by\*\*:.*?\n*\z/m, '')

    CustomMarkdownRenderer.render(cleaned_body)
  end
end
